"""The SD-card drop-in: a firstrun.sh generated for one specific panel.

Raspberry Pi OS runs /boot/firmware/firstrun.sh once, hooked from cmdline.txt
by `systemd.run=`, and Raspberry Pi Imager uses exactly that mechanism for its
own customisation. Dropping our own file there means the panel provisions
itself on first boot: nothing to discover, no IP to find, no SSH.

The catch that shapes the whole design: `systemd.run` executes under
`systemd.unit=kernel-command-line.target`, a minimal target where networking is
not up. So this script cannot fetch anything itself. It does the offline work
-- hostname, user, key -- installs a oneshot unit, and lets the reboot that
follows run the actual provisioning once the network exists.
"""
import shlex

FIRSTRUN = r"""#!/bin/bash
# Panel first-boot setup, generated by the config server for __PANEL_ID__.
# Runs once, then removes itself. Log: <boot>/panel-firstrun.log
#
# Work out where to log BEFORE redirecting. A failed redirect on exec kills the
# shell outright, so hardcoding a path that might not exist or might not be
# mounted this early loses the script and its log in one go -- the worst
# possible failure for something that runs unattended on first boot.
BOOT=/boot/firmware
[ -d "$BOOT" ] || BOOT=/boot
LOG="$BOOT/panel-firstrun.log"
: >>"$LOG" 2>/dev/null || LOG=/var/log/panel-firstrun.log
: >>"$LOG" 2>/dev/null || LOG=/dev/null
exec >>"$LOG" 2>&1
set -x
echo "panel firstrun starting, boot=$BOOT log=$LOG"

PANEL_ID=__PANEL_ID_Q__
HOST_NEW=__HOSTNAME_Q__
SSH_USER=__SSH_USER_Q__
SSH_KEY=__SSH_KEY_Q__
SERVER=__SERVER_Q__
TOKEN=__TOKEN_Q__
HA_TOKEN=__HA_TOKEN_Q__

# ---- hostname -------------------------------------------------------------
echo "$HOST_NEW" > /etc/hostname
hostname "$HOST_NEW" || true
if grep -qE '^127\.0\.1\.1' /etc/hosts; then
  sed -i "s/^127\.0\.1\.1.*/127.0.1.1\t$HOST_NEW/" /etc/hosts
else
  printf '127.0.1.1\t%s\n' "$HOST_NEW" >> /etc/hosts
fi

# ---- login ----------------------------------------------------------------
# Key only, no password: the account exists so there is a way in when
# something goes wrong, and a wall panel should not have a password to leak.
if ! id -u "$SSH_USER" >/dev/null 2>&1; then
  useradd -m -s /bin/bash -G sudo,video,input,render "$SSH_USER"
  passwd -l "$SSH_USER"
fi
HOME_DIR=$(getent passwd "$SSH_USER" | cut -d: -f6)
install -d -m 700 -o "$SSH_USER" -g "$SSH_USER" "$HOME_DIR/.ssh"
# Added to the file, not written over it. This used to be `>`, which discarded
# any key Raspberry Pi Imager had put there -- so a panel imaged with your own
# key came up accepting only the server's, whose private half is on the server.
# The symptom is "Permission denied (publickey)" from a machine that could log
# in yesterday, which reads as a client problem and is not one.
touch "$HOME_DIR/.ssh/authorized_keys"
grep -qxF "$SSH_KEY" "$HOME_DIR/.ssh/authorized_keys" \
  || printf '%s\n' "$SSH_KEY" >> "$HOME_DIR/.ssh/authorized_keys"
chown "$SSH_USER:$SSH_USER" "$HOME_DIR/.ssh/authorized_keys"
chmod 600 "$HOME_DIR/.ssh/authorized_keys"
printf '%s ALL=(ALL) NOPASSWD:ALL\n' "$SSH_USER" > /etc/sudoers.d/010-panel
chmod 440 /etc/sudoers.d/010-panel
systemctl enable ssh >/dev/null 2>&1 || systemctl enable sshd >/dev/null 2>&1 || true

# ---- provisioning, deferred to a networked boot ---------------------------
# Nothing above needed the network. Everything below does, and this script runs
# before networking exists, so it goes in a unit that runs after the reboot.
cat > /usr/local/bin/panel-provision <<PROV
#!/bin/bash
set -x
exec >>/var/log/panel-provision.log 2>&1
for _ in \$(seq 1 60); do
  curl -fsS -o /dev/null "$SERVER/api/me" && break
  sleep 2
done
curl -fsSL "$SERVER/bootstrap.sh?t=$TOKEN" | env PANEL_HA_TOKEN="$HA_TOKEN" bash -s -- "$HOST_NEW"
rc=\$?
# One shot: the token is spent either way, and a retry loop against a consumed
# token would fail forever without saying anything useful.
systemctl disable panel-provision.service
rm -f /usr/local/bin/panel-provision /etc/systemd/system/panel-provision.service
exit \$rc
PROV
chmod 0755 /usr/local/bin/panel-provision

cat > /etc/systemd/system/panel-provision.service <<UNIT
[Unit]
Description=Provision this panel from the config server
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/panel-provision
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT
systemctl enable panel-provision.service

# ---- remove the first-boot hook ------------------------------------------
# Imager's own firstrun.sh does the same: strip systemd.run from cmdline.txt so
# a later boot does not run this again, then delete the script.
sed -i 's| systemd\.run=[^ ]*||g; s| systemd\.run_success_action=[^ ]*||g; s| systemd\.unit=[^ ]*||g' "$BOOT/cmdline.txt"
rm -f "$BOOT/firstrun.sh"
exit 0
"""


def render(panel_id, hostname, ssh_user, ssh_key, server, token, ha_token=""):
    """Substitute by marker, shell-quoted. The script is full of bash ${...}
    and heredocs, which is why this is not str.format."""
    subs = {
        "__PANEL_ID__": panel_id,
        "__PANEL_ID_Q__": shlex.quote(panel_id),
        "__HOSTNAME_Q__": shlex.quote(hostname or panel_id),
        "__SSH_USER_Q__": shlex.quote(ssh_user or "panel-admin"),
        "__SSH_KEY_Q__": shlex.quote(ssh_key.strip()),
        "__SERVER_Q__": shlex.quote(server.rstrip("/")),
        "__TOKEN_Q__": shlex.quote(token),
        "__HA_TOKEN_Q__": shlex.quote(ha_token or ""),
    }
    out = FIRSTRUN
    for k, v in subs.items():
        out = out.replace(k, v)
    return out
