"""Panel config server.

Panels register themselves, heartbeat, and hold a WebSocket so a save in the
GUI reaches them immediately. If the socket is down they fall back to polling;
if this server is down entirely they keep running on their cached config.
Nothing here is ever in the path of a light turning on.
"""
import hashlib
import hmac
import json
import os
import secrets
import shlex
import socket
import threading
import time

from fastapi import Depends, FastAPI, HTTPException, Request, Response, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles


from . import db, firstboot, ha, ssh

ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "changeme")
WEAK_DEFAULTS = {"changeme", "change-me", ""}
PBKDF2_ROUNDS = 200_000
STATIC_DIR = os.path.join(os.path.dirname(__file__), "static")
UI_DIR = os.environ.get("PANEL_UI_DIR", "/data/ui")   # holds panel.html for preview
BUNDLE_DIR = os.environ.get("PANEL_BUNDLE_DIR", "/data/bundle")  # panel.html, agent, backlight
BUILTIN_BUNDLE = os.environ.get("PANEL_BUILTIN_BUNDLE", "")      # baked into the image
# Only needed where the operator reaches the server by a different address than
# the panels do — in practice, behind Home Assistant ingress.
PANEL_URL = os.environ.get("PANEL_URL", "").rstrip("/")

# Generated per panel. Markers rather than str.format: the script is full of
# bash ${...} and heredocs that would fight with brace formatting.
BOOTSTRAP = r"""#!/usr/bin/env bash
# Panel bootstrap — generated by the config server for one specific panel.
set -euo pipefail

SERVER="__SERVER__"
PANEL_ID="__PANEL_ID__"

[ "$(id -u)" = "0" ] || { echo "Run this with sudo." >&2; exit 1; }

# Prompts read from the terminal, not stdin: this script is normally piped
# into bash, so stdin is the script itself and a bare `read` would eat it.
# Must actually open /dev/tty, not just test that it exists. Run over SSH
# without a pty the node is present but opening it fails with ENXIO, so an
# existence check leaves TTY set, the first `read` fails, and set -e kills the
# install partway through.
if [ -t 0 ] || { [ -e /dev/tty ] && (: < /dev/tty) 2>/dev/null; }; then
  TTY=/dev/tty
else
  TTY=""
fi
ask() { # ask VAR "prompt" [silent]
  local __v=$1 __p=$2 __s=${3:-}
  [ -n "$TTY" ] || { echo "No terminal for prompt: $__p" >&2; exit 1; }
  if [ -n "$__s" ]; then read -rsp "$__p" "$__v" < "$TTY"; echo; else read -rp "$__p" "$__v" < "$TTY"; fi
}

# Run from the GUI over SSH there is no terminal, so every prompt has to have a
# non-interactive answer: hostname as $1, and the token in PANEL_HA_TOKEN.
HOST_NEW="${1:-}"
if [ -z "$HOST_NEW" ] && [ -n "$TTY" ]; then
  ask HOST_NEW "Hostname for this panel [$PANEL_ID]: "
fi
HOST_NEW="${HOST_NEW:-$PANEL_ID}"
# Lowercase and strip anything not valid in a hostname. Mixed case is legal but
# sudo and avahi both behave better without it.
HOST_NEW=$(echo "$HOST_NEW" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' | sed 's/^-*//;s/-*$//')
OLD_HOST=$(hostname)
echo "==> hostname: $HOST_NEW"
hostnamectl set-hostname "$HOST_NEW"
# Without this, every later sudo prints "unable to resolve host".
if grep -qE "^127\.0\.1\.1" /etc/hosts; then
  sed -i "s/^127\.0\.1\.1.*/127.0.1.1\t$HOST_NEW/" /etc/hosts
else
  printf '127.0.1.1\t%s\n' "$HOST_NEW" >> /etc/hosts
fi
[ "$OLD_HOST" = "$HOST_NEW" ] || echo "    (was $OLD_HOST)"

echo "==> dependencies"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python3-aiohttp curl

echo "==> panel files"
install -d -m 755 /opt/panel/current
if [ -f /opt/panel/current/panel.html ]; then
  cp -a /opt/panel/current "/opt/panel/backup-$(date +%Y%m%d%H%M%S)"
fi
# curl's own failure here is "(22) The requested URL returned error: 404" with
# no mention of which URL or why, which is not enough to act on.
fetch() {
  if ! curl -fsSL "$1" -o "$2"; then
    echo "ERROR: could not fetch $1" >&2
    echo "       The server has no copy of that file. It normally ships inside" >&2
    echo "       the image; if the server was updated by hand, check its" >&2
    echo "       bundle directory." >&2
    exit 1
  fi
}
fetch "$SERVER/bundle/panel.html"     /opt/panel/current/panel.html
fetch "$SERVER/bundle/panel-agent.py" /usr/local/bin/panel-agent
fetch "$SERVER/bundle/backlight.py"   /usr/local/bin/panel-backlight
chmod +x /usr/local/bin/panel-agent /usr/local/bin/panel-backlight

# The bundle is populated by hand, so it can lag the server. An agent without
# panel-id support ignores the id below and registers under its hostname,
# which silently creates a second, unclaimed panel instead of filling in this
# one -- a confusing failure that looks like "the agent never connected".
if ! grep -q 'panel-id' /usr/local/bin/panel-agent; then
  echo "ERROR: $SERVER/bundle/panel-agent.py predates server-issued panel ids." >&2
  echo "       Copy the current agent/panel-agent.py into the server's bundle" >&2
  echo "       directory and re-run this command." >&2
  exit 1
fi

# Identity comes from the server, not the hostname, so renaming this Pi later
# does not strand its record and create a duplicate.
#
# If the id changed, the config on disk belongs to a different panel record and
# describes another room's lights and speakers. Drop it: the new record starts
# at version 1, so an agent comparing versions would otherwise consider the
# stale config current. secrets.json is kept -- same hardware, same Home
# Assistant, and the token is not identity-specific.
OLD_ID=$(cat /opt/panel/panel-id 2>/dev/null || true)
if [ -n "$OLD_ID" ] && [ "$OLD_ID" != "$PANEL_ID" ]; then
  rm -f /opt/panel/current/config.json
  echo "    cleared config left over from $OLD_ID"
fi
echo "$PANEL_ID" > /opt/panel/panel-id

if [ ! -f /opt/panel/current/secrets.json ]; then
  # Typed on the Pi and never stored by the config server: the panel talks to
  # Home Assistant directly. Installing from the GUI passes it through the
  # server's memory for the length of one SSH command -- never to disk, never
  # to the database -- which is the cost of not having to walk to the panel.
  HA_TOKEN="${PANEL_HA_TOKEN:-}"
  if [ -z "$HA_TOKEN" ] && [ -n "$TTY" ]; then
    ask HA_TOKEN "Home Assistant long-lived token (blank to skip): " silent
  fi
  if [ -n "${HA_TOKEN:-}" ]; then
    printf '{"ha_token": "%s"}\n' "$HA_TOKEN" > /opt/panel/current/secrets.json
    chmod 600 /opt/panel/current/secrets.json
  else
    echo "    skipped — panel will run in demo mode until secrets.json exists"
  fi
fi

echo "==> display"
DSI_OVERLAY=__DSI_OVERLAY_Q__
CONFIG=/boot/firmware/config.txt
[ -f "$CONFIG" ] || CONFIG=/boot/config.txt
NEEDS_REBOOT=0
if [ -z "$DSI_OVERLAY" ]; then
  echo "    no overlay set — correct for the official Touch Display, which is"
  echo "    auto-detected. A third-party panel needs one or it shows no signal."
elif [ -f "$CONFIG" ]; then
  if grep -qxF "dtoverlay=$DSI_OVERLAY" "$CONFIG"; then
    echo "    overlay already present"
  else
    # Once, before anything is modified: taking it again later would overwrite
    # the original with a file this script had already edited.
    cp "$CONFIG" "$CONFIG.panel-backup"
    # Drop any other DSI panel overlay, so changing a panel's screen type
    # replaces the line rather than adding a second, conflicting one.
    if grep -qE '^dtoverlay=vc4-kms-dsi-' "$CONFIG"; then
      sed -i '/^dtoverlay=vc4-kms-dsi-/d' "$CONFIG"
      echo "    replaced a different DSI overlay"
    fi
    grep -q '^dtoverlay=vc4-kms-v3d' "$CONFIG" || printf '\ndtoverlay=vc4-kms-v3d\n' >> "$CONFIG"
    {
      echo "# Set from this panel's Display configuration. Stock Raspberry Pi OS"
      echo "# auto-detects only the official Touch Display, so a third-party"
      echo "# panel with no line here shows no signal at all -- not a blank"
      echo "# desktop, nothing. Append ,dsi0 for the DSI0 connector."
      echo "dtoverlay=$DSI_OVERLAY"
    } >> "$CONFIG"
    echo "    overlay added to $CONFIG (backup: $CONFIG.panel-backup)"
    NEEDS_REBOOT=1
  fi
else
  echo "    WARNING: no config.txt found; set the DSI overlay by hand" >&2
fi

echo "==> kiosk"
# Raspberry Pi OS Lite: no desktop session, no autologin, and no compositor
# autostart. cage runs chromium fullscreen as its only job, supervised by
# systemd. The desktop-session approach this replaces had three autostart
# mechanisms, a session that could restart and orphan the browser, and a
# singleton handoff that showed a white screen with nothing in any log.
# See pi-os/README.md and docs/PI-KIOSK-FINDINGS.md.
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq cage
if ! command -v chromium >/dev/null 2>&1 && ! command -v chromium-browser >/dev/null 2>&1; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq chromium || DEBIAN_FRONTEND=noninteractive apt-get install -y -qq chromium-browser
fi

# A system user with a real home: chromium needs somewhere writable for its
# profile, and the unit sets HOME there explicitly rather than trusting the
# account to have one.
id -u panel >/dev/null 2>&1 || useradd -r -G video,input,render -d /var/lib/panel-kiosk panel
install -d -o panel -g panel -m 0755 /var/lib/panel-kiosk

# The kiosk launcher is fetched, not written here. It used to be a heredoc in
# this script, byte for byte the same file as pi-os/kiosk-launch.sh -- and
# because this script only runs at install time, editing it reached a panel
# only on a reinstall. A release of chromium flags therefore sat on both
# panels doing nothing, which looks exactly like flags that did not work. As
# a bundle file there is one copy of it and it updates itself like the rest.
fetch "$SERVER/bundle/kiosk-launch.sh" /usr/local/bin/panel-kiosk-launch
chmod 0755 /usr/local/bin/panel-kiosk-launch

# The Pi's HDMI ports appear as input devices advertising pointer capability,
# which makes wlroots draw a cursor that a touch-only panel can never move.
cat > /etc/udev/rules.d/99-panel-ignore-hdmi-input.rules <<'UDEVRULE'
# vc4-hdmi-0 and vc4-hdmi-1 are HDMI CEC / jack-detect nodes that the kernel
# exposes as input devices advertising "keyboard pointer". They never emit any
# motion, but wlroots sees a pointer and draws a cursor accordingly -- one that
# nothing on a touch-only panel can ever move or dismiss.
#
# The Goodix touchscreen reports "keyboard touch" with no pointer capability,
# so ignoring these leaves the panel with no pointer devices and no cursor.
#
# The panel is DSI, so nothing here needs HDMI input in the first place.
SUBSYSTEM=="input", ATTRS{name}=="vc4-hdmi*", ENV{LIBINPUT_IGNORE_DEVICE}="1"
UDEVRULE
udevadm control --reload-rules || true
udevadm trigger --subsystem-match=input || true

cat > /etc/systemd/system/cage-kiosk.service <<'CAGEUNIT'
[Unit]
Description=Panel kiosk (cage + chromium)
# panel-agent serves the UI on 127.0.0.1:8088; chromium needs it up first.
# systemd-logind provides the seat/session cage needs for DRM access.
#
# Wants, not Requires: the launch script has its own wait-then-continue
# fallback, and a panel that comes up showing an error beats one that shows
# nothing at all because a dependency failed.
After=panel-agent.service systemd-logind.service network-online.target
Wants=panel-agent.service
# tty1, and getty must not have it. logind only grants DRM master to the
# session on the *active* VT, so a kiosk parked on tty2 while tty1 is
# foreground starts, acquires nothing, and idles forever -- the unit reports
# active (running) with Tasks: 0 and the console stays on screen.
Conflicts=getty@tty1.service
After=getty@tty1.service

[Service]
Type=simple
User=panel
Group=panel
# PAMName+TTYPath registers this service as a real login session with
# systemd-logind, which is what grants cage DRM/input device access without
# hand-rolled udev rules.
PAMName=login
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
StandardInput=tty
StandardOutput=journal
StandardError=journal
UtmpIdentifier=tty1
UtmpMode=user
# Chromium needs a writable HOME for its profile. Set explicitly rather than
# relying on the panel user having a home directory.
Environment=HOME=/var/lib/panel-kiosk
ExecStart=/usr/local/bin/panel-kiosk-launch
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
CAGEUNIT

# Remove the desktop-session kiosk this replaces, so a panel provisioned by an
# older version of this script does not end up running both.
rm -f /usr/local/bin/panel-kiosk
for U in /home/*/.config/autostart/panel-kiosk.desktop; do
  [ -e "$U" ] && rm -f "$U"
done
for A in /home/*/.config/labwc/autostart /home/*/.config/wayfire.ini; do
  [ -e "$A" ] && sed -i '/panel-kiosk/d' "$A"
done
# Drop the browser cache. A panel installed before the agent began sending
# no-store has entries stored under heuristic freshness, which Chromium can
# serve without revalidating — so a reinstall replaces panel.html on disk and
# the panel goes on showing the old one, which reads as the reinstall having
# done nothing at all.
rm -rf /var/lib/panel-kiosk/chromium/Default/Cache \
       "/var/lib/panel-kiosk/chromium/Default/Code Cache" 2>/dev/null || true

NEEDS_REBOOT=1
echo "    cage kiosk installed"

echo "==> services"
cat > /etc/systemd/system/panel-agent.service <<UNIT
[Unit]
Description=Panel config sync agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=PANEL_SERVER=$SERVER
Environment=PANEL_DIR=/opt/panel
# Python buffers stdout in 8KB blocks when it is a pipe, and the journal is a
# pipe. Without this the agent's output only appears once enough of it has
# accumulated -- so a panel that is working quietly logs nothing at all, while
# one failing in a retry loop logs fine. That difference cost several rounds of
# chasing a bug by its silence.
Environment=PYTHONUNBUFFERED=1
ExecStart=/usr/local/bin/panel-agent
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
UNIT

cat > /etc/systemd/system/panel-backlight.service <<UNIT
[Unit]
Description=Panel backlight helper

[Service]
Environment=PYTHONUNBUFFERED=1
ExecStart=/usr/local/bin/panel-backlight
Restart=always

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
# getty must release tty1. logind grants DRM master only to the session on the
# active VT, so a kiosk sitting on tty2 behind a getty starts, acquires
# nothing, and idles -- systemctl reports active (running) with Tasks: 0 while
# the console stays on screen.
systemctl disable --now getty@tty1.service 2>/dev/null || true
systemctl enable panel-agent panel-backlight cage-kiosk
# restart, not `enable --now`: --now does nothing to an already-running unit,
# so a leftover agent from a previous install keeps its old PANEL_SERVER and
# the freshly written unit file is silently ignored.
systemctl restart panel-agent panel-backlight
# cage is deliberately not started here. It wants a seat on tty2 and the DSI
# overlay may only have just been added, so it starts cleanly on the reboot
# this script asks for rather than half-working over SSH.

echo "    agent server: $(systemctl show -p Environment --value panel-agent | tr ' ' '\n' | grep PANEL_SERVER || echo '(unset)')"

echo "==> waiting for the agent to reach the server"
for _ in $(seq 1 20); do
  # Tolerant of spacing: FastAPI emits {"seen":true} with no space, and an
  # exact-match pattern here silently never fires -- the agent registers and
  # the installer still reports failure.
  if curl -fsS "$SERVER/api/panel_seen/$PANEL_ID" | grep -qE '"seen":[[:space:]]*true'; then
    echo
    echo "Done. $HOST_NEW is registered as $PANEL_ID."
    echo "Point Chromium at http://127.0.0.1:8088/panel.html"
    if [ "$NEEDS_REBOOT" = "1" ]; then
      # Rebooted for you: until it happens the screen stays blank, so leaving
      # it to the operator means staring at a dead panel with no way to tell
      # whether the install finished. Backgrounded so this session returns its
      # output and exit status first.
      echo "Rebooting in 5 seconds to start the panel."
      (sleep 5; systemctl reboot) >/dev/null 2>&1 &
    fi
    exit 0
  fi
  sleep 2
done

echo >&2
echo "The agent did not reach $SERVER within 40s." >&2
echo "Panel id it should be reporting: $PANEL_ID" >&2
echo >&2
echo "--- systemctl status panel-agent ---" >&2
systemctl --no-pager --lines=0 status panel-agent >&2 || true
echo "--- last 25 log lines ---" >&2
journalctl -u panel-agent -n 25 --no-pager >&2 || true
echo >&2
echo "If the log shows the agent registering under a different id, the fleet" >&2
echo "now has a stray unclaimed panel -- remove it and re-run this command." >&2
exit 1
"""

app = FastAPI(title="Panel Config Server")
db.init()

# Installs in progress, polled by the browser. In memory on purpose: an install
# is a one-off someone is watching, and a server restart mid-install means
# starting over regardless, so there is nothing worth persisting.
INSTALL_JOBS: dict[str, dict] = {}
INSTALL_JOBS_MAX = 8


def _run_install(job_id, host, user, url, hostname, ha_token, port):
    job = INSTALL_JOBS[job_id]
    try:
        for chunk in ssh.bootstrap_lines(host, user, url, hostname, ha_token, port):
            job["lines"].extend(chunk.splitlines())
    except Exception as e:
        job["lines"].append(f"install failed: {e.__class__.__name__}: {e}")
    finally:
        job["ok"] = any(ssh.DONE + "0 ===" in ln for ln in job["lines"])
        job["done"] = True


# panel_id -> WebSocket
LIVE: dict[str, WebSocket] = {}
# session token -> expiry
SESSIONS: dict[str, float] = {}
SESSION_TTL = 60 * 60 * 12


# ---------------------------------------------------------------- auth
def _session_ok(request: Request) -> bool:
    tok = request.cookies.get("psid")
    exp = SESSIONS.get(tok or "")
    return bool(exp and exp > time.time())


def require_admin(request: Request):
    if not _session_ok(request):
        raise HTTPException(status_code=401, detail="not authenticated")
    return True


def _hash_password(pw: str) -> str:
    salt = secrets.token_bytes(16)
    dk = hashlib.pbkdf2_hmac("sha256", pw.encode(), salt, PBKDF2_ROUNDS)
    return f"pbkdf2_sha256${PBKDF2_ROUNDS}${salt.hex()}${dk.hex()}"


def _verify_password(pw: str, stored: str) -> bool:
    try:
        _algo, rounds, salt_hex, hash_hex = stored.split("$")
        dk = hashlib.pbkdf2_hmac("sha256", pw.encode(), bytes.fromhex(salt_hex), int(rounds))
        return hmac.compare_digest(dk.hex(), hash_hex)
    except Exception:
        return False


def check_password(pw: str) -> bool:
    """A password set in the GUI is stored hashed and wins. Falling back to the
    env var keeps an existing deployment working before anyone visits Settings."""
    stored = db.get_setting("admin_password_hash")
    if stored:
        return _verify_password(pw, stored)
    return hmac.compare_digest(
        hashlib.sha256(pw.encode()).hexdigest(),
        hashlib.sha256(ADMIN_PASSWORD.encode()).hexdigest(),
    )


@app.post("/api/login")
async def login(request: Request, response: Response):
    body = await request.json()
    if not check_password(body.get("password") or ""):
        raise HTTPException(status_code=401, detail="wrong password")
    tok = secrets.token_urlsafe(32)
    SESSIONS[tok] = time.time() + SESSION_TTL
    response.set_cookie("psid", tok, httponly=True, samesite="lax", max_age=SESSION_TTL)
    return {"ok": True}


@app.post("/api/logout")
async def logout(request: Request, response: Response):
    SESSIONS.pop(request.cookies.get("psid", ""), None)
    response.delete_cookie("psid")
    return {"ok": True}


@app.get("/api/me")
async def me(request: Request):
    return {"authenticated": _session_ok(request), "ha_configured": ha.configured()}


# ---------------------------------------------------------------- panel-facing
@app.post("/api/register")
async def register(request: Request):
    b = await request.json()
    pid = b.get("panel_id") or b.get("mac") or b.get("hostname")
    if not pid:
        raise HTTPException(400, "panel_id, mac or hostname required")
    p = db.upsert_panel(
        pid, b.get("hostname", pid), b.get("mac"), b.get("ip"),
        b.get("kind", "pi"), b.get("version"),
    )
    return {
        "panel_id": pid,
        "claimed": bool(p["claimed"]),
        "config_version": db.latest_version(pid),
    }


@app.post("/api/heartbeat")
async def heartbeat(request: Request):
    b = await request.json()
    pid = b.get("panel_id")
    if not pid or not db.get_panel(pid):
        raise HTTPException(404, "unknown panel")
    db.touch(pid, b.get("metrics"), b.get("config_version"))
    return {"config_version": db.latest_version(pid)}


@app.get("/api/config/{panel_id}")
async def panel_config(panel_id: str):
    p = db.get_panel(panel_id)
    if not p:
        raise HTTPException(404, "unknown panel")
    cfg = db.merged_config(panel_id)
    cfg["_version"] = db.latest_version(panel_id)
    cfg["_panel_id"] = panel_id
    cfg["_claimed"] = bool(p["claimed"])
    return cfg


@app.websocket("/api/ws/{panel_id}")
async def panel_ws(ws: WebSocket, panel_id: str):
    await ws.accept()
    LIVE[panel_id] = ws
    try:
        await ws.send_json({"type": "hello", "config_version": db.latest_version(panel_id)})
        while True:
            msg = await ws.receive_text()
            try:
                data = json.loads(msg)
            except Exception:
                continue
            if data.get("type") == "heartbeat":
                db.touch(panel_id, data.get("metrics"), data.get("config_version"))
                await ws.send_json({"type": "ack", "config_version": db.latest_version(panel_id)})
    except WebSocketDisconnect:
        pass
    except Exception:
        pass
    finally:
        if LIVE.get(panel_id) is ws:
            LIVE.pop(panel_id, None)


async def notify(panel_id: str, payload: dict):
    ws = LIVE.get(panel_id)
    if not ws:
        return False
    try:
        await ws.send_json(payload)
        return True
    except Exception:
        LIVE.pop(panel_id, None)
        return False


# ---------------------------------------------------------------- admin API
@app.get("/api/panels", dependencies=[Depends(require_admin)])
async def panels():
    out = db.list_panels()
    for p in out:
        p["live"] = p["id"] in LIVE
    return out


@app.get("/api/panels/{panel_id}", dependencies=[Depends(require_admin)])
async def panel_detail(panel_id: str):
    p = db.get_panel(panel_id)
    if not p:
        raise HTTPException(404, "unknown panel")
    cfg = db.merged_config(panel_id)
    return {
        "panel": p,
        "config": cfg,
        "own": db.get_config(panel_id) or {},
        "history": db.config_history(panel_id),
        "latest_version": db.latest_version(panel_id),
        "problems": await ha.validate_config(cfg),
        "live": panel_id in LIVE,
    }


@app.post("/api/panels/{panel_id}/claim", dependencies=[Depends(require_admin)])
async def claim(panel_id: str, request: Request):
    b = await request.json()
    p = db.claim(panel_id, b.get("room", ""), b.get("template", "default"), b.get("room_label"))
    await notify(panel_id, {"type": "config_updated", "version": db.latest_version(panel_id)})
    return p


@app.put("/api/panels/{panel_id}/config", dependencies=[Depends(require_admin)])
async def put_config(panel_id: str, request: Request):
    if not db.get_panel(panel_id):
        raise HTTPException(404, "unknown panel")
    data = await request.json()
    data.pop("_version", None)
    v = db.save_config(panel_id, data)
    pushed = await notify(panel_id, {"type": "config_updated", "version": v})
    return {"version": v, "pushed": pushed}


@app.post("/api/panels/{panel_id}/rollback", dependencies=[Depends(require_admin)])
async def rollback(panel_id: str, request: Request):
    b = await request.json()
    old = db.get_config(panel_id, int(b["version"]))
    if not old:
        raise HTTPException(404, "no such version")
    old.pop("_version", None)
    v = db.save_config(panel_id, old)
    await notify(panel_id, {"type": "config_updated", "version": v})
    return {"version": v}


@app.post("/api/panels/{panel_id}/action", dependencies=[Depends(require_admin)])
async def action(panel_id: str, request: Request):
    b = await request.json()
    act = b.get("action")
    if act not in ("reload", "restart", "sync"):
        raise HTTPException(400, "unknown action")
    ok = await notify(panel_id, {"type": act})
    return {"sent": ok}


@app.delete("/api/panels/{panel_id}", dependencies=[Depends(require_admin)])
async def remove(panel_id: str):
    """Forget the device. If the hardware is still alive it will re-register
    as unclaimed, which is the intended behaviour — this is 'forget', not 'ban'."""
    db.delete_panel(panel_id)
    ws = LIVE.pop(panel_id, None)
    if ws:
        try:
            await ws.close()
        except Exception:
            pass
    return {"ok": True}


@app.post("/api/push_all", dependencies=[Depends(require_admin)])
async def push_all():
    sent, queued = [], []
    for p in db.list_panels():
        if not p["claimed"]:
            continue
        v = db.latest_version(p["id"])
        if await notify(p["id"], {"type": "config_updated", "version": v}):
            sent.append(p["hostname"])
        else:
            queued.append(p["hostname"])
    return {"sent": sent, "queued": queued}


@app.get("/api/push_all/preview", dependencies=[Depends(require_admin)])
async def push_all_preview():
    rows = []
    for p in db.list_panels():
        if not p["claimed"]:
            continue
        rows.append({
            "hostname": p["hostname"],
            "room": p["room"],
            "online": p["id"] in LIVE,
            "running": p["config_version"],
            "latest": db.latest_version(p["id"]),
        })
    return rows


# ---------------------------------------------------------------- templates
@app.get("/api/templates", dependencies=[Depends(require_admin)])
async def templates():
    return db.list_templates()


@app.get("/api/templates/{name}", dependencies=[Depends(require_admin)])
async def template(name: str):
    t = db.get_template(name)
    if t is None:
        raise HTTPException(404, "no such template")
    return t


@app.put("/api/templates/{name}", dependencies=[Depends(require_admin)])
async def put_template(name: str, request: Request):
    db.save_template(name, await request.json())
    return {"ok": True}


# ---------------------------------------------------------------- HA helpers
@app.get("/api/entities", dependencies=[Depends(require_admin)])
async def entities(domain: str = "", q: str = ""):
    domains = [d for d in domain.split(",") if d] or None
    return await ha.entities(domains, q)


# ---------------------------------------------------------------- provisioning
def _local_ip() -> str:
    """This host's address on the LAN.

    No packet is sent; the kernel just picks the interface it would route out
    of. Under the add-on that is the Home Assistant host itself, because
    host_network puts the container on its network stack.
    """
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("8.8.8.8", 80))
        return s.getsockname()[0]
    except Exception:
        return ""
    finally:
        s.close()


def _panel_url(request: Request) -> tuple[str, str]:
    """The address a *panel* uses to reach this server, and where it came from.

    Not the address the operator is using. Behind Home Assistant ingress the
    admin request arrives through HA's proxy, so request.base_url is an ingress
    URL — it needs HA's auth and is internal to HA, so a panel handed it can
    never fetch anything. The Supervisor marks those requests with
    X-Ingress-Path, which is how that case is recognised rather than guessed.
    """
    saved = db.get_setting("panel_url")
    if saved:
        return saved.rstrip("/"), "settings"
    if PANEL_URL:
        return PANEL_URL.rstrip("/"), "env"
    if request.headers.get("X-Ingress-Path"):
        ip = _local_ip()
        if ip:
            return f"http://{ip}:8099", "host"
        return "", "unresolved"
    return str(request.base_url).rstrip("/"), "request"


def _server_url(request: Request) -> str:
    return _panel_url(request)[0]


@app.post("/api/provision", dependencies=[Depends(require_admin)])
async def provision(request: Request):
    """Create the panel record and a one-time token before the Pi exists."""
    b = await request.json()
    room = (b.get("room") or "").strip()
    if not room:
        raise HTTPException(400, "room is required")
    pid = db.create_provisional_panel(room, b.get("template"), b.get("room_label"))
    token = db.create_token(pid)
    return {
        "panel_id": pid,
        "token": token,
        "command": f"curl -fsSL {_server_url(request)}/bootstrap.sh?t={token} | sudo bash",
    }


@app.post("/api/panels/{panel_id}/reprovision", dependencies=[Depends(require_admin)])
async def reprovision(panel_id: str, request: Request):
    """Issue a fresh token for a panel that already exists.

    Re-running the installer used to mean creating a second panel record, which
    hands out a new id and abandons the room's config and history. This keeps
    the id, so the bootstrap leaves config.json alone and the panel comes back
    as itself — same room, same entities, same version history.

    Reinstalling is how a panel picks up a new panel.html or agent, since those
    are fetched once at provisioning and not after.
    """
    if not db.get_panel(panel_id):
        raise HTTPException(404, "unknown panel")
    db.clear_tokens(panel_id)
    token = db.create_token(panel_id)
    return {
        "panel_id": panel_id,
        "token": token,
        "command": f"curl -fsSL {_server_url(request)}/bootstrap.sh?t={token} | sudo bash",
    }


@app.get("/api/provision", dependencies=[Depends(require_admin)])
async def provision_pending(request: Request):
    base = _server_url(request)
    return [
        dict(t, command=f"curl -fsSL {base}/bootstrap.sh?t={t['token']} | sudo bash")
        for t in db.pending_tokens()
    ]


@app.post("/api/provision/{token}/run", dependencies=[Depends(require_admin)])
async def provision_run(token: str, request: Request):
    """Install onto a panel over SSH.

    Gated on the token still being unused, which is the whole security model:
    the server can only reach hardware it is currently provisioning, never a
    panel already in service. Config changes for those go through the agent,
    which is why nothing here needs to touch them.
    """
    b = await request.json()
    host = (b.get("host") or "").strip()
    user = (b.get("user") or "").strip()
    if not host or not user:
        raise HTTPException(400, "host and user are required")
    # host:port accepted inline, so a panel on a non-default sshd port does not
    # need its own field in the form.
    port = int(b.get("port") or 22)
    if host.count(":") == 1 and not host.startswith("["):
        host, _, p = host.partition(":")
        if p.isdigit():
            port = int(p)

    pending = [t for t in db.pending_tokens() if t["token"] == token]
    if not pending:
        raise HTTPException(404, "unknown or already-used token")

    url = f"{_server_url(request)}/bootstrap.sh?t={token}"
    # Runs the same curl-pipe-bash the GUI hands out for manual installs, so
    # there is one provisioning path rather than two that can drift. Fetching
    # that URL is what consumes the token.
    #
    # Run as a background job the browser polls, rather than streamed. A
    # streamed response arrived in one lump behind Home Assistant's ingress
    # proxy, which buffers -- so the install looked hung for several minutes,
    # the exact problem streaming was added to solve. Polling cannot be
    # buffered into uselessness by anything in between.
    job_id = secrets.token_urlsafe(8)
    INSTALL_JOBS[job_id] = {"lines": [], "done": False, "ok": False, "at": time.time()}
    for old in sorted(INSTALL_JOBS, key=lambda k: INSTALL_JOBS[k]["at"])[:-INSTALL_JOBS_MAX]:
        INSTALL_JOBS.pop(old, None)
    threading.Thread(
        target=_run_install, daemon=True,
        args=(job_id, host, user, url, (b.get("hostname") or "").strip(),
              b.get("ha_token") or "", port),
    ).start()
    return {"job": job_id}


@app.get("/api/provision/run/{job_id}", dependencies=[Depends(require_admin)])
async def provision_run_status(job_id: str, offset: int = 0):
    """Lines since `offset`, so a poll only carries what is new."""
    job = INSTALL_JOBS.get(job_id)
    if not job:
        raise HTTPException(404, "unknown or expired install")
    return {"lines": job["lines"][offset:], "offset": len(job["lines"]),
            "done": job["done"], "ok": job["ok"]}


@app.post("/api/provision/{token}/firstrun", dependencies=[Depends(require_admin)])
async def provision_firstrun(token: str, request: Request):
    """The SD-card drop-in for this panel.

    Deliberately does not consume the token: the file is generated before the
    card is even flashed, and the token is spent when the panel fetches
    bootstrap.sh on first boot.
    """
    b = await request.json()
    pending = [t for t in db.pending_tokens() if t["token"] == token]
    if not pending:
        raise HTTPException(404, "unknown or already-used token")
    body = firstboot.render(
        panel_id=pending[0]["panel_id"],
        hostname=(b.get("hostname") or "").strip(),
        ssh_user=(b.get("ssh_user") or "").strip(),
        ssh_key=ssh.public_key(),
        server=_server_url(request),
        token=token,
        ha_token=b.get("ha_token") or "",
    )
    return Response(content=body, media_type="text/x-shellscript", headers={
        "Content-Disposition": 'attachment; filename="firstrun.sh"'})


@app.post("/api/scan", dependencies=[Depends(require_admin)])
async def scan_network(request: Request):
    """Look for candidate panels on the LAN.

    Finding a freshly flashed Pi otherwise means logging into the router. The
    default network is derived from HA_URL, which is already an IP on the same
    LAN, so in practice there is nothing to type.
    """
    b = await request.json()
    cidr = (b.get("cidr") or "").strip() or _default_cidr()
    if not cidr:
        raise HTTPException(400, "no network to scan — set one, or set HA_URL first")
    try:
        hosts = await ssh.scan(cidr)
    except ValueError as e:
        raise HTTPException(400, str(e))
    known = {p.get("ip"): p for p in db.list_panels() if p.get("ip")}
    for h in hosts:
        p = known.get(h["ip"])
        h["known_panel"] = p["hostname"] if p else ""
    return {"cidr": cidr, "hosts": hosts}


def _default_cidr():
    """The /24 this server is on, else the one HA_URL points at.

    Own address first because it is always right and never configured. HA_URL
    used to be the only source, which broke as soon as the add-on started
    getting Home Assistant through the Supervisor: that URL is
    http://supervisor/core and contains no address at all, so scanning failed
    with "set one, or set HA_URL first" on a server that knew perfectly well
    where it was.
    """
    import re
    for candidate in (_local_ip(), ha.url()):
        m = re.search(r"\b(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.\d{1,3}\b", candidate or "")
        if m:
            return f"{m.group(1)}.{m.group(2)}.{m.group(3)}.0/24"
    return ""


@app.get("/api/panel_seen/{panel_id}")
async def panel_seen(panel_id: str):
    """Unauthenticated by design: the bootstrap script calls this to confirm its
    own agent came up, before any admin session exists on that machine. It
    reveals only whether an id has ever checked in."""
    p = db.get_panel(panel_id)
    return {"seen": bool(p and p.get("last_seen"))}


@app.get("/bootstrap.sh")
async def bootstrap(request: Request, t: str = ""):
    """The token is the credential — this runs on a Pi with no session."""
    pid = db.consume_token(t)
    if not pid:
        raise HTTPException(404, "unknown or already-used token")
    # The DSI overlay is per panel: a 5-inch and a 4.3-inch Waveshare need
    # different lines, and the official display needs none at all.
    overlay = (db.merged_config(pid).get("display") or {}).get("dsi_overlay", "")
    body = (BOOTSTRAP
            .replace("__SERVER__", _server_url(request))
            .replace("__PANEL_ID__", pid)
            .replace("__DSI_OVERLAY_Q__", shlex.quote(overlay or "")))
    return Response(content=body, media_type="text/x-shellscript")


BUNDLE_FILES = ("panel.html", "panel-agent.py", "backlight.py", "kiosk-launch.sh")


def _bundle_path(name):
    """Operator copy wins, then the copy shipped in the image."""
    for d in (BUNDLE_DIR, BUILTIN_BUNDLE):
        if d and os.path.exists(os.path.join(d, name)):
            return os.path.join(d, name)
    return None


@app.get("/bundle/manifest")
async def bundle_manifest(request: Request):
    """Hashes of the panel files, so an agent can tell whether it is current.

    Hashes rather than a version number: nothing to remember to bump, and it
    notices a file edited by hand on either end. Unauthenticated like the rest
    of /bundle — it describes files any panel may already fetch.
    """
    _note_bundle(request, "manifest", "served")
    out = {}
    for name in BUNDLE_FILES:
        path = _bundle_path(name)
        if not path:
            continue
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        out[name] = {"sha256": h.hexdigest(), "size": os.path.getsize(path)}
    return out


# Recent bundle traffic, newest last, keyed by source address. Purely a
# diagnostic and deliberately in memory: the question it answers is "is this
# panel asking for files right now", which nothing persistent improves.
#
# It exists because there was no way to tell a panel that never asked from one
# that asked and could not install what it got. Both present as a panel that
# does not update, and the only instrument was a shell on the panel.
BUNDLE_LOG: list = []
BUNDLE_LOG_MAX = 200


def _note_bundle(request: Request, name: str, status: str):
    ip = request.client.host if request.client else "?"
    BUNDLE_LOG.append({"ip": ip, "file": name, "status": status, "at": time.time()})
    del BUNDLE_LOG[:-BUNDLE_LOG_MAX]


@app.get("/bundle/{name}")
async def bundle(name: str, request: Request):
    """Panel files the bootstrap script pulls. Not secret — panel.html is served
    to every panel anyway — but path-checked so it can only reach these dirs.

    /data/bundle wins so a panel can be pinned to a hand-edited build, but the
    copy shipped in the image is the normal source. Hand-populating this was
    the cause of a stale agent, a stale panel.html and an empty directory on a
    fresh install, each of which presented as something else entirely.
    """
    if name not in BUNDLE_FILES:
        _note_bundle(request, name, "unknown")
        raise HTTPException(404, "unknown bundle file")
    path = _bundle_path(name)
    if not path:
        _note_bundle(request, name, "missing")
        raise HTTPException(404, f"{name} is in neither {BUNDLE_DIR} nor the image")
    _note_bundle(request, name, "served")
    return FileResponse(path)


@app.get("/api/bundle-log", dependencies=[Depends(require_admin)])
async def bundle_log():
    """What the panels have actually asked for, and where each file is served
    from. `source` matters: a stale hand-copied file in /data/bundle wins over
    the image and freezes a panel at whatever was left there."""
    where = {}
    for name in BUNDLE_FILES:
        p = _bundle_path(name)
        where[name] = ("operator (/data/bundle)" if p and p.startswith(BUNDLE_DIR)
                       else "image" if p else "MISSING")
    return {"serving": where, "recent": list(reversed(BUNDLE_LOG))}


# ---------------------------------------------------------------- settings
@app.get("/api/settings", dependencies=[Depends(require_admin)])
async def get_settings(request: Request):
    """The token is never returned — only whether one is set and its last four
    characters, which is enough to tell two tokens apart."""
    tok = ha.token()
    return {
        "ha_url": ha.url(),
        "ha_token_set": bool(tok),
        "ha_token_hint": ("…" + tok[-4:]) if tok else "",
        "ha_configured": ha.configured(),
        "ha_last_error": ha.last_error(),
        "sources": ha.source(),
        "admin_password_source": "settings" if db.get_setting("admin_password_hash") else "env",
        "admin_password_is_default": (
            not db.get_setting("admin_password_hash") and ADMIN_PASSWORD in WEAK_DEFAULTS
        ),
        "ssh_public_key": ssh.public_key(),
        # The resolved value, not just where it came from. A panel is handed
        # this exact string, so it is the only thing worth showing.
        "panel_url": db.get_setting("panel_url") or PANEL_URL,
        "panel_url_effective": _panel_url(request)[0],
        "panel_url_source": _panel_url(request)[1],
        "server": {
            "db_path": db.DB_PATH,
            "ui_dir": UI_DIR,
            "preview_ui_present": os.path.exists(os.path.join(UI_DIR, "panel.html")),
            "session_ttl_hours": round(SESSION_TTL / 3600),
        },
    }


@app.put("/api/settings", dependencies=[Depends(require_admin)])
async def put_settings(request: Request):
    b = await request.json()
    if "ha_url" in b:
        v = (b.get("ha_url") or "").strip().rstrip("/")
        # Clearing removes the row rather than storing "", so the value falls
        # back to the env var and the GUI can honestly say where it came from.
        if v:
            db.set_setting("ha_url", v)
        else:
            db.clear_setting("ha_url")
    if "panel_url" in b:
        v = (b.get("panel_url") or "").strip().rstrip("/")
        if v:
            db.set_setting("panel_url", v)
        else:
            db.clear_setting("panel_url")
    if b.get("clear_ha_token"):
        db.clear_setting("ha_token")
    elif (b.get("ha_token") or "").strip():
        db.set_setting("ha_token", b["ha_token"].strip())
    ha.invalidate()
    return await get_settings(request)


@app.post("/api/settings/test_ha", dependencies=[Depends(require_admin)])
async def test_ha(request: Request):
    """Test before saving, so a bad token can't lock the dropdowns out."""
    b = await request.json()
    return await ha.check((b.get("ha_url") or "").strip(), (b.get("ha_token") or "").strip())


@app.post("/api/settings/password", dependencies=[Depends(require_admin)])
async def set_password(request: Request):
    b = await request.json()
    if not check_password(b.get("current") or ""):
        raise HTTPException(status_code=400, detail="current password is wrong")
    new = b.get("new") or ""
    if len(new) < 8:
        raise HTTPException(status_code=400, detail="new password must be at least 8 characters")
    db.set_setting("admin_password_hash", _hash_password(new))
    # Every other session was authenticated with the old password.
    keep = request.cookies.get("psid", "")
    for t in [t for t in SESSIONS if t != keep]:
        SESSIONS.pop(t, None)
    return {"ok": True}


@app.get("/api/preview/{panel_id}/states", dependencies=[Depends(require_admin)])
async def preview_states(panel_id: str):
    """State for the live preview — proxied so no token reaches the browser."""
    cfg = db.merged_config(panel_id)
    wanted = set()
    for l in cfg.get("lights") or []:
        wanted.add(l.get("entity_id"))
    media = cfg.get("media") or {}
    wanted.add(media.get("default_speaker"))
    for sp in media.get("speakers") or []:
        wanted.add(sp.get("entity_id") if isinstance(sp, dict) else sp)
    sens = cfg.get("sensors") or {}
    wanted.update([sens.get("temperature"), sens.get("humidity")])
    wanted.discard(None); wanted.discard("")
    return [s for s in await ha.states() if s.get("entity_id") in wanted]


# ---------------------------------------------------------------- static
@app.get("/preview/panel.html", dependencies=[Depends(require_admin)])
async def preview_ui():
    path = os.path.join(UI_DIR, "panel.html")
    if not os.path.exists(path):
        return JSONResponse({"error": f"panel.html not found in {UI_DIR}"}, status_code=404)
    return FileResponse(path)


@app.middleware("http")
async def no_cache_html(request: Request, call_next):
    """Never let a browser hold on to the admin UI.

    It is one self-contained HTML file, so a cached copy means old JavaScript
    talking to a new API — which is not an obvious failure. After an update it
    showed a new field's value as "not set", because the old code did not know
    that value existed. Nothing about that says "you are looking at a stale
    page". The file is ~40KB; re-fetching it costs nothing worth having.
    """
    response = await call_next(request)
    if request.url.path in ("/", "/index.html"):
        response.headers["Cache-Control"] = "no-store, must-revalidate"
    return response


app.mount("/", StaticFiles(directory=STATIC_DIR, html=True), name="static")
